---
name: Issue Report
description: Report a bug in the ChoreOps integration
title: "[ISSUE] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please complete this form to report a bug in ChoreOps.

        Before filing, check the troubleshooting guide:
        [ChoreOps troubleshooting wiki](https://github.com/ccpk1/choreops/wiki/Technical:-Troubleshooting)

  - type: input
    id: home_assistant_version
    attributes:
      label: Home Assistant version
      description: "What version of Home Assistant are you running?"
      placeholder: "e.g., 2026.2.4"
    validations:
      required: true

  - type: input
    id: integration_version
    attributes:
      label: ChoreOps integration version
      description: "What ChoreOps version are you using?"
      placeholder: "e.g., 0.5.0b5"
    validations:
      required: true

  - type: dropdown
    id: installation_method
    attributes:
      label: Installation method
      description: "How did you install ChoreOps?"
      options:
        - HACS
        - Manual
    validations:
      required: true

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: "Confirm both items before submitting."
      options:
        - label: I checked for existing open and closed issues
          required: true
        - label: I updated ChoreOps (or confirmed the issue still occurs on the latest version)
          required: true
        - label: I enabled debug logging and can share logs
          required: true

  - type: dropdown
    id: issue_scope
    attributes:
      label: Issue scope
      description: "Where does this issue appear to occur?"
      options:
        - Integration logic/state
        - Dashboard UI/template
        - Both integration and dashboard
        - Not sure
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: "List the exact steps needed to reproduce this issue."
      placeholder: |
        1. Go to...
        2. Configure...
        3. Trigger...
        4. Observe...
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: Issue description
      description: "Describe what happened and what you expected to happen."
      placeholder: "Provide a detailed description..."
    validations:
      required: true

  - type: input
    id: relevant_entities
    attributes:
      label: Relevant entity IDs (optional)
      description: "List related entities if known (for example: sensor.alex_choreops_chore_status_brush_teeth)."
      placeholder: "sensor... , button..."

  - type: markdown
    attributes:
      value: |
        ### Logs

        Preferred method: enable debug logging from **Settings → Devices & Services → Integrations → ChoreOps → Enable debug logging**.

        Alternative method: add the following to `configuration.yaml`, then restart Home Assistant:

        ```yaml
        logger:
          default: warning
          logs:
            custom_components.choreops: debug
        ```

        See [Home Assistant logger documentation](https://www.home-assistant.io/integrations/logger) for more details.

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Paste relevant log lines here (remove tokens, passwords, and personal data)."
      render: shell

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: "Add anything else that may help us diagnose the issue."
      placeholder: "Any additional information..."
---
